spring.application.name=app

# ── Base de datos ──────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.ywmnssihfzlxyfmoubhc&password=Smillio777.
spring.datasource.username=postgres.ywmnssihfzlxyfmoubhc
spring.datasource.password=Smillio777.
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ── Base de datos ──────────────────────────────
##spring.datasource.url=jdbc:mysql://localhost:3306/smilio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
##spring.datasource.username=smilio_user
##spring.datasource.password=smilio_pass
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ────────────────────────────
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.format_sql=true