version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smilio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: smilio
      MYSQL_USER: smilio_user
      MYSQL_PASSWORD: smilio_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: